### ISSUE TITLE
Converting to theme

### ISSUE THREAD

**Issue by akzhy** [athul/OSC--Website#4]
## Two things

1. Are you sure that this starter is the best idea ? I mean it was built for portfolios and this website doesn't look much like a portfolio. [This can be converted to a suitable one if required]

2. If you are going with this, use the theme so that future updates will be automatically added. I have already fixed two minor bugs.

**Comment by athul** [comment]
Okay.Theme is relatively new and you published it fast. Switching to theme

**Comment by athul** [comment]
So Il'l Remove all the commits and Force Push to this repo Thats Right?

**Comment by athul** [comment]
Plus @akzhy you did submit the theme right?

**Comment by athul** [comment]
Plus I tried and it turns out I have no idea how Themes work :sweaty_smile: Could you clone this and make the basic changes and push this?

**Comment by akzhy** [comment]
Submitted @athul
